# Generated by Django 4.2.7 on 2023-12-18 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=100, verbose_name='Nom du client')),
                ('adresse', models.CharField(blank=True, max_length=100, null=True, verbose_name='Adresse du client')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client')),
                ('telephone', models.CharField(max_length=15, verbose_name='Téléphone du client')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.CreateModel(
            name='TypeChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='Nom du type de chambre')),
                ('prix_nuit', models.IntegerField(verbose_name='Prix par nuit')),
                ('prix_heure', models.IntegerField(verbose_name='Prix par heure')),
                ('description', models.TextField(verbose_name='Description du type de chambre')),
            ],
            options={
                'verbose_name': 'Type de chambre',
                'verbose_name_plural': 'Types de chambres',
            },
        ),
        migrations.CreateModel(
            name='Chambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Numéro de chambre')),
                ('etat', models.CharField(choices=[('disponible', 'Disponible'), ('indisponible', 'Indisponible'), ('renovation', 'En rénovation'), ('construction', 'En construction')], default='disponible', max_length=20, verbose_name='État de la chambre')),
                ('nombre_lits', models.PositiveIntegerField(verbose_name='Nombre de lits')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description de la chambre')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('type_chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gesthotel.typechambre', verbose_name='Type de chambre')),
            ],
            options={
                'verbose_name': 'Chambre',
                'verbose_name_plural': 'Chambres',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='AffectationChambre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('heure_debut', models.TimeField(verbose_name='Heure de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('heure_fin', models.TimeField(verbose_name='Heure de fin')),
                ('client_anonyme', models.BooleanField(default=False, verbose_name='Client anonyme')),
                ('chambre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gesthotel.chambre', verbose_name='Chambre')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gesthotel.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Affectation de chambre',
                'verbose_name_plural': 'Affectations de chambres',
            },
        ),
    ]
