# Generated by Django 4.2.7 on 2023-12-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesthotel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PiecesJointes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=255, null=True, verbose_name='Titre de la pièce jointe')),
                ('contenu', models.TextField(blank=True, null=True, verbose_name='Contenu de la pièce jointe')),
                ('piece_jointe', models.FileField(blank=True, null=True, upload_to='pieces_jointes/', verbose_name='Pièce jointe')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Ajouter des pièces joints',
                'verbose_name_plural': 'Ajouter des pièces joints',
            },
        ),
        migrations.AlterField(
            model_name='chambre',
            name='etat',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('nettoyage', 'En nettoyage'), ('indisponible', 'Indisponible'), ('renovation', 'En rénovation'), ('construction', 'En construction')], default='disponible', max_length=20, verbose_name='État de la chambre'),
        ),
    ]
