# Generated by Django 4.2.7 on 2023-12-18 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesthotel', '0002_piecesjointes_alter_chambre_etat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_notification', models.CharField(max_length=255)),
                ('date_notification', models.DateField()),
                ('heure_notification', models.TimeField()),
            ],
        ),
    ]
