# Generated by Django 4.2.7 on 2023-12-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesthotel', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chambre',
            name='etat',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('nettoyage', 'En nettoyage'), ('indisponible', 'Indisponible')], default='disponible', max_length=20, verbose_name='État de la chambre'),
        ),
    ]
