# Generated by Django 4.2.7 on 2023-12-20 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gesthotel', '0004_alter_chambre_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affectationchambre',
            name='date_debut',
            field=models.DateTimeField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='affectationchambre',
            name='date_fin',
            field=models.DateTimeField(verbose_name='Date de fin'),
        ),
    ]
