# Generated by Django 4.2.3 on 2023-11-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='fonction',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='fonctions', to='utilisateurs.permission'),
        ),
    ]
