# Generated by Django 4.2.7 on 2023-11-28 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilisateurs', '0003_utilisateurs_action_recentaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recent_actions_utilisateurs', to=settings.AUTH_USER_MODEL),
        ),
    ]
