# Generated by Django 4.2.7 on 2023-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_prenom', models.CharField(max_length=50, verbose_name='Nom')),
                ('date_naissance', models.DateField(verbose_name='Date de naissance')),
                ('nationalite', models.CharField(max_length=255, verbose_name='Nationalité')),
                ('lieu_naissance', models.CharField(max_length=255, verbose_name='Lieu de naissance')),
                ('numero_cni', models.CharField(max_length=255, verbose_name='Numéro CNI')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('Autre', 'Autre')], max_length=10, verbose_name='Genre')),
                ('poste', models.CharField(choices=[('Receptionniste', 'Réceptionniste'), ('Concierge', 'Concierge'), ('Service de chambre', 'Service de chambre'), ('Gestionnaire', 'Gestionnaire'), ('Autre', 'Autre')], max_length=50, verbose_name='Poste')),
                ('date_embauche', models.DateField(verbose_name="Date d'embauche")),
                ('statut', models.CharField(choices=[('Actif', 'Actif'), ('Inactif', 'Inactif'), ('En congé', 'En congé'), ('Autre', 'Autre')], max_length=20, verbose_name='Statut')),
                ('adresse', models.TextField(verbose_name='Adresse')),
                ('telephone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse e-mail')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images/')),
                ('piece_identite_recto', models.FileField(blank=True, null=True, upload_to='pieces_identite/', verbose_name="Pièce d'identité - Recto")),
                ('piece_identite_verso', models.FileField(blank=True, null=True, upload_to='pieces_identite/', verbose_name="Pièce d'identité - Verso")),
            ],
            options={
                'verbose_name': 'Personnel',
                'verbose_name_plural': 'Personnel',
            },
        ),
        migrations.RemoveField(
            model_name='historicaladministratif',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaladministratif',
            name='user',
        ),
        migrations.DeleteModel(
            name='Administratif',
        ),
        migrations.DeleteModel(
            name='HistoricalAdministratif',
        ),
    ]
